// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateService.proto

package kill.me.palas.grpc;

public final class UpdateServiceOuterClass {
  private UpdateServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code kill.me.palas.grpc.ElementType}
   */
  public enum ElementType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>topic = 0;</code>
     */
    topic(0),
    /**
     * <code>test = 1;</code>
     */
    test(1),
    /**
     * <code>lecture = 2;</code>
     */
    lecture(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>topic = 0;</code>
     */
    public static final int topic_VALUE = 0;
    /**
     * <code>test = 1;</code>
     */
    public static final int test_VALUE = 1;
    /**
     * <code>lecture = 2;</code>
     */
    public static final int lecture_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ElementType valueOf(int value) {
      return forNumber(value);
    }

    public static ElementType forNumber(int value) {
      switch (value) {
        case 0: return topic;
        case 1: return test;
        case 2: return lecture;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ElementType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ElementType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ElementType>() {
            public ElementType findValueByNumber(int number) {
              return ElementType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return UpdateServiceOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ElementType[] VALUES = values();

    public static ElementType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ElementType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kill.me.palas.grpc.ElementType)
  }

  /**
   * Protobuf enum {@code kill.me.palas.grpc.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>create = 0;</code>
     */
    create(0),
    /**
     * <code>update = 1;</code>
     */
    update(1),
    /**
     * <code>delete = 2;</code>
     */
    delete(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>create = 0;</code>
     */
    public static final int create_VALUE = 0;
    /**
     * <code>update = 1;</code>
     */
    public static final int update_VALUE = 1;
    /**
     * <code>delete = 2;</code>
     */
    public static final int delete_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return create;
        case 1: return update;
        case 2: return delete;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return UpdateServiceOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kill.me.palas.grpc.ActionType)
  }

  public interface UpdateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kill.me.palas.grpc.UpdateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string course = 1;</code>
     */
    String getCourse();
    /**
     * <code>string course = 1;</code>
     */
    com.google.protobuf.ByteString
        getCourseBytes();

    /**
     * <code>string element = 2;</code>
     */
    String getElement();
    /**
     * <code>string element = 2;</code>
     */
    com.google.protobuf.ByteString
        getElementBytes();

    /**
     * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
     */
    int getElementTypeValue();
    /**
     * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
     */
    ElementType getElementType();

    /**
     * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
     */
    int getActionTypeValue();
    /**
     * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
     */
    ActionType getActionType();
  }
  /**
   * Protobuf type {@code kill.me.palas.grpc.UpdateRequest}
   */
  public  static final class UpdateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kill.me.palas.grpc.UpdateRequest)
      UpdateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateRequest.newBuilder() to construct.
    private UpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateRequest() {
      course_ = "";
      element_ = "";
      elementType_ = 0;
      actionType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              course_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              element_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              elementType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              actionType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateRequest.class, Builder.class);
    }

    public static final int COURSE_FIELD_NUMBER = 1;
    private volatile Object course_;
    /**
     * <code>string course = 1;</code>
     */
    public String getCourse() {
      Object ref = course_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        course_ = s;
        return s;
      }
    }
    /**
     * <code>string course = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseBytes() {
      Object ref = course_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        course_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENT_FIELD_NUMBER = 2;
    private volatile Object element_;
    /**
     * <code>string element = 2;</code>
     */
    public String getElement() {
      Object ref = element_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        element_ = s;
        return s;
      }
    }
    /**
     * <code>string element = 2;</code>
     */
    public com.google.protobuf.ByteString
        getElementBytes() {
      Object ref = element_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        element_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENTTYPE_FIELD_NUMBER = 3;
    private int elementType_;
    /**
     * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
     */
    public int getElementTypeValue() {
      return elementType_;
    }
    /**
     * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
     */
    public ElementType getElementType() {
      @SuppressWarnings("deprecation")
      ElementType result = ElementType.valueOf(elementType_);
      return result == null ? ElementType.UNRECOGNIZED : result;
    }

    public static final int ACTIONTYPE_FIELD_NUMBER = 4;
    private int actionType_;
    /**
     * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
     */
    public int getActionTypeValue() {
      return actionType_;
    }
    /**
     * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
     */
    public ActionType getActionType() {
      @SuppressWarnings("deprecation")
      ActionType result = ActionType.valueOf(actionType_);
      return result == null ? ActionType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCourseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, course_);
      }
      if (!getElementBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, element_);
      }
      if (elementType_ != ElementType.topic.getNumber()) {
        output.writeEnum(3, elementType_);
      }
      if (actionType_ != ActionType.create.getNumber()) {
        output.writeEnum(4, actionType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCourseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, course_);
      }
      if (!getElementBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, element_);
      }
      if (elementType_ != ElementType.topic.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, elementType_);
      }
      if (actionType_ != ActionType.create.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, actionType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UpdateRequest)) {
        return super.equals(obj);
      }
      UpdateRequest other = (UpdateRequest) obj;

      if (!getCourse()
          .equals(other.getCourse())) return false;
      if (!getElement()
          .equals(other.getElement())) return false;
      if (elementType_ != other.elementType_) return false;
      if (actionType_ != other.actionType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COURSE_FIELD_NUMBER;
      hash = (53 * hash) + getCourse().hashCode();
      hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getElement().hashCode();
      hash = (37 * hash) + ELEMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + elementType_;
      hash = (37 * hash) + ACTIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + actionType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UpdateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UpdateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UpdateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kill.me.palas.grpc.UpdateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kill.me.palas.grpc.UpdateRequest)
        UpdateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UpdateRequest.class, Builder.class);
      }

      // Construct using kill.me.palas.grpc.UpdateServiceOuterClass.UpdateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        course_ = "";

        element_ = "";

        elementType_ = 0;

        actionType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateRequest_descriptor;
      }

      @Override
      public UpdateRequest getDefaultInstanceForType() {
        return UpdateRequest.getDefaultInstance();
      }

      @Override
      public UpdateRequest build() {
        UpdateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UpdateRequest buildPartial() {
        UpdateRequest result = new UpdateRequest(this);
        result.course_ = course_;
        result.element_ = element_;
        result.elementType_ = elementType_;
        result.actionType_ = actionType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UpdateRequest) {
          return mergeFrom((UpdateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UpdateRequest other) {
        if (other == UpdateRequest.getDefaultInstance()) return this;
        if (!other.getCourse().isEmpty()) {
          course_ = other.course_;
          onChanged();
        }
        if (!other.getElement().isEmpty()) {
          element_ = other.element_;
          onChanged();
        }
        if (other.elementType_ != 0) {
          setElementTypeValue(other.getElementTypeValue());
        }
        if (other.actionType_ != 0) {
          setActionTypeValue(other.getActionTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UpdateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UpdateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object course_ = "";
      /**
       * <code>string course = 1;</code>
       */
      public String getCourse() {
        Object ref = course_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          course_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string course = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCourseBytes() {
        Object ref = course_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          course_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string course = 1;</code>
       */
      public Builder setCourse(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        course_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string course = 1;</code>
       */
      public Builder clearCourse() {
        
        course_ = getDefaultInstance().getCourse();
        onChanged();
        return this;
      }
      /**
       * <code>string course = 1;</code>
       */
      public Builder setCourseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        course_ = value;
        onChanged();
        return this;
      }

      private Object element_ = "";
      /**
       * <code>string element = 2;</code>
       */
      public String getElement() {
        Object ref = element_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          element_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string element = 2;</code>
       */
      public com.google.protobuf.ByteString
          getElementBytes() {
        Object ref = element_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          element_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string element = 2;</code>
       */
      public Builder setElement(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        element_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string element = 2;</code>
       */
      public Builder clearElement() {
        
        element_ = getDefaultInstance().getElement();
        onChanged();
        return this;
      }
      /**
       * <code>string element = 2;</code>
       */
      public Builder setElementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        element_ = value;
        onChanged();
        return this;
      }

      private int elementType_ = 0;
      /**
       * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
       */
      public int getElementTypeValue() {
        return elementType_;
      }
      /**
       * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
       */
      public Builder setElementTypeValue(int value) {
        elementType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
       */
      public ElementType getElementType() {
        @SuppressWarnings("deprecation")
        ElementType result = ElementType.valueOf(elementType_);
        return result == null ? ElementType.UNRECOGNIZED : result;
      }
      /**
       * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
       */
      public Builder setElementType(ElementType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        elementType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.kill.me.palas.grpc.ElementType elementType = 3;</code>
       */
      public Builder clearElementType() {
        
        elementType_ = 0;
        onChanged();
        return this;
      }

      private int actionType_ = 0;
      /**
       * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
       */
      public int getActionTypeValue() {
        return actionType_;
      }
      /**
       * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
       */
      public Builder setActionTypeValue(int value) {
        actionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
       */
      public ActionType getActionType() {
        @SuppressWarnings("deprecation")
        ActionType result = ActionType.valueOf(actionType_);
        return result == null ? ActionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
       */
      public Builder setActionType(ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        actionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.kill.me.palas.grpc.ActionType actionType = 4;</code>
       */
      public Builder clearActionType() {
        
        actionType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kill.me.palas.grpc.UpdateRequest)
    }

    // @@protoc_insertion_point(class_scope:kill.me.palas.grpc.UpdateRequest)
    private static final UpdateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UpdateRequest();
    }

    public static UpdateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateRequest>() {
      @Override
      public UpdateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public UpdateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kill.me.palas.grpc.UpdateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     */
    String getText();
    /**
     * <code>string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code kill.me.palas.grpc.UpdateResponse}
   */
  public  static final class UpdateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kill.me.palas.grpc.UpdateResponse)
      UpdateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateResponse.newBuilder() to construct.
    private UpdateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateResponse() {
      text_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateResponse.class, Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UpdateResponse)) {
        return super.equals(obj);
      }
      UpdateResponse other = (UpdateResponse) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UpdateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UpdateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kill.me.palas.grpc.UpdateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kill.me.palas.grpc.UpdateResponse)
        UpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UpdateResponse.class, Builder.class);
      }

      // Construct using kill.me.palas.grpc.UpdateServiceOuterClass.UpdateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        text_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UpdateServiceOuterClass.internal_static_kill_me_palas_grpc_UpdateResponse_descriptor;
      }

      @Override
      public UpdateResponse getDefaultInstanceForType() {
        return UpdateResponse.getDefaultInstance();
      }

      @Override
      public UpdateResponse build() {
        UpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UpdateResponse buildPartial() {
        UpdateResponse result = new UpdateResponse(this);
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UpdateResponse) {
          return mergeFrom((UpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UpdateResponse other) {
        if (other == UpdateResponse.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UpdateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UpdateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object text_ = "";
      /**
       * <code>string text = 1;</code>
       */
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setText(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kill.me.palas.grpc.UpdateResponse)
    }

    // @@protoc_insertion_point(class_scope:kill.me.palas.grpc.UpdateResponse)
    private static final UpdateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UpdateResponse();
    }

    public static UpdateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateResponse>
        PARSER = new com.google.protobuf.AbstractParser<UpdateResponse>() {
      @Override
      public UpdateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public UpdateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kill_me_palas_grpc_UpdateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kill_me_palas_grpc_UpdateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kill_me_palas_grpc_UpdateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kill_me_palas_grpc_UpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023UpdateService.proto\022\022kill.me.palas.grp" +
      "c\"\232\001\n\rUpdateRequest\022\016\n\006course\030\001 \001(\t\022\017\n\007e" +
      "lement\030\002 \001(\t\0224\n\013elementType\030\003 \001(\0162\037.kill" +
      ".me.palas.grpc.ElementType\0222\n\nactionType" +
      "\030\004 \001(\0162\036.kill.me.palas.grpc.ActionType\"\036" +
      "\n\016UpdateResponse\022\014\n\004text\030\001 \001(\t*/\n\013Elemen" +
      "tType\022\t\n\005topic\020\000\022\010\n\004test\020\001\022\013\n\007lecture\020\002*" +
      "0\n\nActionType\022\n\n\006create\020\000\022\n\n\006update\020\001\022\n\n" +
      "\006delete\020\0022`\n\rUpdateService\022O\n\006update\022!.k" +
      "ill.me.palas.grpc.UpdateRequest\032\".kill.m" +
      "e.palas.grpc.UpdateResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kill_me_palas_grpc_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kill_me_palas_grpc_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kill_me_palas_grpc_UpdateRequest_descriptor,
        new String[] { "Course", "Element", "ElementType", "ActionType", });
    internal_static_kill_me_palas_grpc_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kill_me_palas_grpc_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kill_me_palas_grpc_UpdateResponse_descriptor,
        new String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
